Pages/Admin/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using YouthGroup.Data;
using System.ComponentModel.DataAnnotations;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using YouthGroup.Pages.Admin;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;

//Author: Jack Puschnigg


namespace YouthGroup.Pages.Admin
{
    //Allows only Admins to view 'create posts' page
    [Authorize(Roles = "ADMIN")]
    public class CreateModel : PageModel
    {

        //Declare variables needed to store post data
        public static string ImageName { set; get; }

        public static bool ToDelete { get; set; }

        public static int postCounter { get; set; }

        [BindProperty]
        public IFormFile Image { set; get; }

        [BindProperty]
        public Post Post { get; set; }


        private static YouthGroup.Data.ApplicationDbContext _context;
        private readonly IHostingEnvironment hostingEnvironment;

        public CreateModel(YouthGroup.Data.ApplicationDbContext context, IHostingEnvironment environment)
        {
            hostingEnvironment = environment;
            _context = context;
        }

        public IActionResult OnGet()
        {

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            //Stays on same page if posts are deleted
            if (ToDelete.Equals(true) && IndexModel.Posts.Count == 1)
            {
                return RedirectToPage("./Create");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            //Verifies the image file is valid
            if (Image != null)
            {
                var fileName = GetUniqueName(Image.FileName);
                var uploads = Path.Combine(hostingEnvironment.WebRootPath, "img");
                var filePath = Path.Combine(uploads, fileName);
                Image.CopyTo(new FileStream(filePath, FileMode.Create));
                ImageName = fileName; // Set the file name
                Post.ImageName = ImageName;
            }

            //Used to count the current number of posted images
            //Prevents flex card stretching
            postCounter++;

            //Instantiate the time
            Post.Time = DateTime.Now.ToString();

            //Deletes posts if necessary
            if (ToDelete.Equals(true))
            {
                for (int i = 0; i < IndexModel.Posts.Count(); i++)
                {
                    _context.Posts.Remove(IndexModel.Posts[i]);
                }

                ToDelete = false;
            }

            await _context.Posts.AddAsync(Post);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        //Creates image file path/URL
        private string GetUniqueName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                   + "_" + Guid.NewGuid().ToString().Substring(0, 4)
                   + Path.GetExtension(fileName);
        }

        //Deletes the posts from the database when the 'delete posts' button is clicked
        public async Task<IActionResult> OnPostDelete()
        {
            ToDelete = true;

            if (ToDelete.Equals(true) && IndexModel.Posts.Count == 1)
            {
                ToDelete = false;
                return RedirectToPage("./Create");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Image != null)
            {
                var fileName = GetUniqueName(Image.FileName);
                var uploads = Path.Combine(hostingEnvironment.WebRootPath, "img");
                var filePath = Path.Combine(uploads, fileName);
                Image.CopyTo(new FileStream(filePath, FileMode.Create));
                ImageName = fileName; // Set the file name
                Post.ImageName = ImageName;
                Post.Time = DateTime.Now.ToString();
            }

            if (ToDelete.Equals(true))
            {
                for (int i = 0; i < IndexModel.Posts.Count(); i++)
                {
                    _context.Posts.Remove(IndexModel.Posts[i]);
                }

                postCounter = 0;

                ToDelete = false;
            }

            await _context.Posts.AddAsync(Post);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using YouthGroup.Data;

namespace YouthGroup.Pages.Admin
{
    public class DeleteModel : PageModel
    {
        private readonly YouthGroup.Data.ApplicationDbContext _context;

        public DeleteModel(YouthGroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public User User { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.SiteUsers.FirstOrDefaultAsync(m => m.ID == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.SiteUsers.FindAsync(id);

            if (User != null)
            {
                _context.SiteUsers.Remove(User);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using YouthGroup.Data;

namespace YouthGroup.Pages.Admin
{
    public class DetailsModel : PageModel
    {
        private readonly YouthGroup.Data.ApplicationDbContext _context;

        public DetailsModel(YouthGroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public User User { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.SiteUsers.FirstOrDefaultAsync(m => m.ID == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Admin/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YouthGroup.Data;

namespace YouthGroup.Pages.Admin
{
    public class EditModel : PageModel
    {
        private readonly YouthGroup.Data.ApplicationDbContext _context;

        public EditModel(YouthGroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public User User { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.SiteUsers.FirstOrDefaultAsync(m => m.ID == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(User).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(User.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool UserExists(int id)
        {
            return _context.SiteUsers.Any(e => e.ID == id);
        }
    }
}

Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using YouthGroup.Data;

//Author: Jack Puschnigg

namespace YouthGroup.Pages.Admin
{
    //Allows only Admins and apporved users to view posts
    [Authorize(Roles = "ADMIN, USER")]
    public class IndexModel : PageModel
    {
        private readonly YouthGroup.Data.ApplicationDbContext _context;

        public IndexModel(YouthGroup.Data.ApplicationDbContext context)
        {
            _context = context;
        }
        public static List<Post> Posts { get; set; }

        public async Task OnGetAsync()
        {
            Posts = (from Posts in _context.Posts.Take(10)
                              select Posts).ToList();
        }
    }
}

Pages/UserRoles/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using YouthGroup.Data;

namespace YouthGroup.Pages.UserRoles
{
    [Authorize(Roles = "ADMIN")]
    public class CreateModel : PageModel
    {
        private readonly YouthGroup.Data.ApplicationDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;

        //By injecting the role manager (and editing the services) you can create/delete roles
        public CreateModel(YouthGroup.Data.ApplicationDbContext context, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
        }

        public IList<Microsoft.AspNetCore.Identity.IdentityRole> Roles { get;set; }

        [BindProperty]
        public string NewRole { get; set; } = "";

        public async Task OnGetAsync()
        {
            Roles = await _roleManager.Roles.ToListAsync();
        }

        public async Task OnPostAsync()
        {
            if (NewRole != "")
            {
                bool exists = await _roleManager.RoleExistsAsync(NewRole.Trim().ToUpper());

                if (!exists)
                {
                    await _roleManager.CreateAsync(new IdentityRole(NewRole.Trim().ToUpper()));
                }
            }

            Roles = await _roleManager.Roles.ToListAsync();
            NewRole = "";
        }
    }
}

Pages/Admin/Create.cshtml
@page
@model YouthGroup.Pages.Admin.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<!-- Author: Jack Puschnigg -->


<h1>Create A New Post</h1>

<!-- Forms that accept info for creating a new post such as title, desc, etc. -->
<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Name</label>
        <input asp-for="Post.Name" class="form-control" placeholder="First and Last name">
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput2">Post Title</label>
        <input asp-for="Post.Title" class="form-control" placeholder="Create a Title">
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Post Description</label>
        <textarea class="form-control" asp-for="Post.Desc" rows="3" placeholder="Write a Short Description"></textarea>
    </div>
    <div class="form-group">
        <input type="file" asp-for="Image" />
    </div>

    <!-- Submit and delete posts button -->
    <button type="submit" class="btn btn-primary mb-2" value="submit" style="background-color: #52ab98; border: none">Submit</button>
    <button type="submit" class="btn btn-primary mb-2" value="delete" asp-page-handler="Delete" style="background-color: #52ab98; border: none">Delete All Posts</button>
</form>

<div>
    <a asp-page="Index" class="btn btn-primary mb-2" style="background-color: #52ab98; border: none">Back to Posts</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Admin/Delete.cshtml
@page
@model YouthGroup.Pages.Admin.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.Password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Password)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="User.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Admin/Details.cshtml
@page
@model YouthGroup.Pages.Admin.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.Password)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Password)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.User.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Admin/Edit.cshtml
@page
@model YouthGroup.Pages.Admin.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="User.ID" />
            <div class="form-group">
                <label asp-for="User.FirstName" class="control-label"></label>
                <input asp-for="User.FirstName" class="form-control" />
                <span asp-validation-for="User.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.LastName" class="control-label"></label>
                <input asp-for="User.LastName" class="form-control" />
                <span asp-validation-for="User.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.Email" class="control-label"></label>
                <input asp-for="User.Email" class="form-control" />
                <span asp-validation-for="User.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.Password" class="control-label"></label>
                <input asp-for="User.Password" class="form-control" />
                <span asp-validation-for="User.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}